version: '2'
services:
    automationservicehub-app:
        image: automationservicehub #localhost:5000/automationservicehub For building via Jenkins
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://automationservicehub-mysql:3306/automationservicehub?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 7778:7778
    automationservicehub-mysql:
        extends:
            file: mysql.yml
            service: automationservicehub-mysql
