version: '2'
services:
    espbroker-app:
        image: espbroker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://espbroker-mysql:3306/espbroker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    espbroker-mysql:
        extends:
            file: mysql.yml
            service: espbroker-mysql
