version: '2'
services:
    automationservicehub-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/AutomationServiceHub/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=automationservicehub
        ports:
            - 3311:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
